name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Npm
        run: |
          npm ci
          npm run test
      - name: Codecov
        uses: codecov/codecov-action@v4
  integration-tests-uppercase-transformation:
    uses: ./.github/workflows/reusable-integration-tests.yml
    with:
        name-transformation: uppercase
        parse-json-secrets: true
        secret-ids: |
            SampleSecret1
            SAMPLESECRET1_ALIAS, SampleSecret1
            /special/chars/secret
            0/special/chars/secret
            PrefixSecret*
            JsonSecret
  integration-tests-lowercase-transformation:
    uses: ./.github/workflows/reusable-integration-tests.yml
    with:
        name-transformation: lowercase
        parse-json-secrets: true
        secret-ids: |
            SampleSecret1
            samplesecret1_alias, SampleSecret1
            /special/chars/secret
            0/special/chars/secret
            PrefixSecret*
            JsonSecret
  integration-tests-no-transformation:
    uses: ./.github/workflows/reusable-integration-tests.yml
    with:
        name-transformation: none
        parse-json-secrets: true
        secret-ids: |
            SampleSecret1
            SampleSecret1_Alias, SampleSecret1
            /special/chars/secret
            0/special/chars/secret
            PrefixSecret*
            JsonSecret
