name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read    
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          npm ci
          npm run test
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::851725216489:role/GithubOIDC-Role-tbc3aSzaVlM0
          aws-region: us-west-2
      - name: Load secrets
        uses: ./
        with:
          secret-ids:
            my_secret*
      - name: Verify secrets
        run: |
          # if [ "$"]
          #echo `env | grep my_secret| base64`
          echo `echo $MY_SECRET_B | base64`
      - name: Codecov
        uses: codecov/codecov-action@v4
