name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          npm ci
          # npm run test
      - name: Build
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654453185:role/GithubActionsRole
          aws-region: us-east-1
      - name: Load secrets
        uses: ./
        with:
          secret-ids:
            MyTestSecret2
            MyTestSecret*
      - name: Verify secrets
        run: |
          if [ "$MYTESTSECRET2" != "MyTestSecret2" ]; then
            exit 1
          fi
      - name: Codecov
        uses: codecov/codecov-action@v4
